spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: customer-service
logging:
  level:
    root: "debug"
    org.springframework.web: "debug"
    org.hibernate: "debug"

